### ISSUE TITLE
There's a problem with the sign in, it asks for verification through email.

### ISSUE THREAD

**Issue by princ-EZ** [Sudococommunity/free-xbox-ultimate#5]
Someone decided to be greedy and steal the account, can you please recover it.

**Comment by Sudococommunity** [comment]
Can you send a screenshot, also stealing the account is pretty impossible cause it has 2 factor authentication and you have to throw money to bypass the 2 factor which isn't cheap , I can login into the account without any problem 😕 so what is the issue

**Comment by Sudococommunity** [comment]
Try changing last digit of pass like -02 ,-03 ,-04 and also if you have put incorrect password let it cooldown for 1 hr 🙃 so that it will not ask you for verification , let me guess the verification mail start with su******@gmail.com I also tried to steal the account but failed

**Comment by princ-EZ** [comment]
> to

It says I have to verify my identity through an email, I waited for an hour and still nothing, I'm pretty sure someone sent a password change and it triggered a security alert

**Comment by princ-EZ** [comment]
> Can you send a screenshot, also stealing the account is pretty impossible cause it has 2 factor authentication and you have to throw money to bypass the 2 factor which isn't cheap , I can login into the account without any problem 😕 so what is the issue

![IMG_20240909_131152](https://github.com/user-attachments/assets/db7fcd0f-b404-4af2-93a0-60926355fff3)

**Comment by princ-EZ** [comment]
Did you solve it? I still can't access the account,
